name: 'Setup Ruby for use with actions'
description: 'Setup a Ruby environment and add it to the PATH'
author: 'GitHub'
inputs: 
  version:
    description: 'The Ruby version to use. Defaults to >= 2.4'
    default: '>= 2.4'
runs:
  using: 'node'
  main: 'lib/main.js'